obj-$(CONFIG_PRIZE_LCD_BIAS) += lcdbias/
obj-$(CONFIG_PRIZE_HALL) += hall/
obj-$(CONFIG_PRIZE_TORCH) += torch/
obj-$(CONFIG_PRIZE_BAROMETER_H5804) += h5804/
obj-$(CONFIG_PRIZE_FM_ANT_SWITCH) += fm_ant/
