ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GSL1691/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/


obj-y += gsl_ts_driver.o
obj-y += gsl_point_id_point_active_pen_no_gesture.o

