# begin, prize-lifenfen-20181213, add for smartpa awinic aw8898
# obj-$(CONFIG_MTK_SMARTPA_SOUND) += auddrv_nxp.o
obj-$(CONFIG_SND_SMARTPA_NXP) += auddrv_nxp.o
#for AWINIC AW8898 Smart PA
obj-$(CONFIG_SND_SMARTPA_AW8898)    += aw8898/
obj-$(CONFIG_SND_SMARTPA_AW88194A)  += aw88194a/
# end, prize-lifenfen-20181213, add for smartpa awinic aw8898
